name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - master  # Deploy on push to master branch
  workflow_dispatch:  # Allow manual trigger from Actions tab

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create build directory
        run: mkdir -p build

      - name: Copy Unity build files to build directory
        run: |
          cp -r Build/* build/
          cp index.html build/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build